// Generated by Wrangler on Tue Jun 25 2024 09:30:46 GMT+0700 (Indochina Time)
// by running `wrangler types`

interface Env {
	shopStorage: KVNamespace;
	APP_NAME: "SwagSanctions";
	APP_SECRET: "SwagSanctions";
	db: D1Database;
}
