#:schema node_modules/wrangler/config-schema.json
name = "sanctions-app"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
id = "5d86805260f1414b9761c8b08b012e51"
binding = "shopStorage"

[[d1_databases]]
binding = "db" # available in your Worker on env.DB
database_name = "test_db"
database_id = "5d86805260f1414b9761c8b08b012e51"

[vars]
APP_NAME = "SwagSanctions"
APP_SECRET = "SwagSanctions"