on:
    push:
        branches:
            - main

jobs:
    backend:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '22'

            -   name: Install dependencies
                run: npm install

            #            - name: Run Migrations
            #              run: npx wrangler d1 migrations apply db --remote
            #              env:
            #                  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
            #                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

            -   name: Deploy
                run: npx wrangler deploy
                env:
                    CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
                    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    frontend:
        runs-on: ubuntu-latest
        needs:
            - backend
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '22'

            -   name: Install dependencies
                working-directory: client
                run: npm install

            -   name: Build
                working-directory: client
                run: npm run build

            -   name: Deploy
                run: npx wrangler pages deploy dist/ --project-name=sanctions-app-client
                working-directory: client
                env:
                    CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
                    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

